services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "spring-user"
      POSTGRES_PASSWORD: "apppw"
    ports:
      - "17432:5432"
    container_name: "deals-db"
    volumes:
      - D:\WORK\deals-pg-data:/var/lib/postgresql/data
    networks:
      - app-network      
  app:
    depends_on:
      - db
    image: deals-app:latest
    environment:
      DEALS_CHECKER_REST_URL: "http://checker-app:8080/api/v1/checker"
      SPRING_KAFKA_CONCURRENCY: 10
      APP_NAME: "deals-app"
    container_name: "deals-app"
    ports:
      - "11080:8080"
    volumes:
      - D:\WORK\logs:/etc/logs
    networks:
      - app-network
  app2:
    depends_on:
      - db
    image: deals-app:latest
    environment:
      DEALS_CHECKER_REST_URL: "http://checker-app:8080/api/v1/checker"
      SPRING_KAFKA_CONCURRENCY: 10
      APP_NAME: "deals-app-2"
    container_name: "deals-app-2"
    ports:
      - "12080:8080"
    volumes:
      - D:\WORK\logs:/etc/logs
    networks:
      - app-network
networks:
  app-network:
    name: app-network
    external: true