openapi: 3.0.1
info:
  title: Checker API
  version: 1.0.0
servers:
  - url: http://checker-app:8080
paths:
  /check-deal:
    get:
      summary: Check Deal
      operationId: checkDeal
      parameters:
        - name: 'deal-date'
          in: header
          schema:
            type: string
            format: date
        - name: 'investor-code'
          in: header
          schema:
            type: string
            maxLength: 7
            minLength: 5
        - name: 'security-code'
          in: header
          schema:
            type: string
            minLength: 10
            maxLength: 10
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CheckResponse"
components:
  schemas:
    CheckResponse:
      type: string